version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: 10.0.43.10
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Secret55
      WORDPRESS_DB_NAME: wordpress
    restart: unless-stopped
